---
  # Notreally sure if this is the right place
  # to put this
  name: App | Add Dependencies
    - libsqlite3-dev
    - libmysqlclient-dev
    - libpq-dev
    - git
    - nodejs
    - npm
  app_short_name: app
  app_env: production
  app_domain: domain.local
  app_secret: 82d58d3dfb91238b495a311eb8539edf5064784f1d58994679db8363ec241c745bef0b446bfe44d66cbf91a2f4e497d8f6b1ef1656e3f405b0d263a9617ac75e
  # TODO change app seceret
  app_repository:  app_repository: https://github.com/RailsApps/rails-devise.git
  app_repository_keyname: id_rsa_app
  app_base_dir: /var/ww
  app_www_root: "{{app_base_dir}}/public"

  app_env_vars:
    - {name: SECRET_KEY_BASE, value: "{{app_Secret}}" } # TODO figure out how to properly install secrets
    - {name: DATABASE_URL, value: "postgres://{{app_db_name}}"}
    - {name: RAILS_ENV, value: "{{app_env}}" }
    - {name: DOMAIN_NAME, value: "{{app_domain}}"}

 app_db_host: localhost
 app_db_user: app_user
 app_db_password: app_password
 app_db_name: app_database

 app_directories:
   - "{{app_base_dir}}"

   
