# https://www.codeproject.com/articles/1086496/deploying-ruby-application-with-ansible
---
  - name: Check if chruby is present
    stat: # stat determines if file is present @ path, if so it registers a value
      path: /usr/local/bin/chruby-exec
    register: chruby
    tags: ruby # tags are only used to run specifc parts of the playbooks


#  - name: Report if chruby is present
#    debug:
#      msg: Chruby is present
#    when: chruby_present.stat.exists

#  - name: Report if chruby is missing
#    debug:
#      msg: Chruby is missing
  #  when: not chruby_present.stat.exists

  - name: Download chruby distribution
    get_url: url="http://github.com/postmodern/chruby/archive/v{{ chruby_version }}.tar.gz"
      dest="/tmp/chruby-{{ chruby_version }}.tar.gz"
    when: not chruby.stat.exists
    tags: ruby

  - name: Unpack chruby
    command: tar xf "/tmp/chruby-{{ chruby_version }}.tar.gz"
    args:
      chdir: "/tmp"
    when: not chruby.stat.exists
    tags: ruby

  - name: Chruby install target
    command: make install
      chdir="tmp/chruby-{{ chruby_version }}"
    become: yes
    when: not chruby.stat.exists
    tags: ruby

  - name: Autoload Chruby script
    template: src="/templates/ch_ruby.sh.j2" dest=/etc/profile.d/chruby.sh
    become: yes
    tags: ruby
