---
  - name: Account Setup
    hosts: all
    become: yes
    become_method: sudo
    remote_user: ubuntu
    tasks:
       - import_tasks: password_management.yml
       - import_tasks: create_deploy_user.yml
       - import_tasks: deploy_keys.yml

# https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary
# try creating a seperate playboook with a remote user of deploy

  - name: Setup Ruby
    hosts: all
    become: yes
    become_method: sudo
    remote_user: deploy
    vars: # creates variables which can be used in templates
      chruby_version: 0.3.9
      ruby_install_version: 0.8.5
      rubies_location: '/home/deploy'
      ruby_version: 3.1.1

    tasks:
      - import_tasks: chruby_install.yml
      - import_tasks: ruby_install_install.yml
      - import_tasks: ruby_install.yml

# in vagrant file you specified ansible.tags = "ruby" to only run ruby tags
