---
  - name: Provision Rails Server
    hosts: all
    become: yes
    become_method: sudo
    remote_user: ubuntu
    tasks:
      - import_tasks: password_management.yml
      - import_tasks: create_deploy_user.yml
      - import_tasks: install_rbenv_and_ruby.yml
      # import_tasks: install_nginx_and_passenger.yml
      # import_tasks: configure_server.yml
      # import_tasks: install_postgres.yml
      # import_tasks: configure_postgres.yml
