---
  # checks if the ruby install tool is present
  - name: Ruby | Check if ruby_install is present
    shell: test -x /usr/local/bin/ruby-install
    when: ansible_system == "Linux"
    ignore_errors: yes
    register: rubyinstall_present
    tags: ruby

  - name: Ruby | Ruby install | package dependencies
    apt: pkg={{ item }} state: present force="yes" update_cache="yes"
    when: ansible_system == "Linux"
    with_items:
      - buil-essentials
      - libffi-dev
      - libgdbm-dev
      - libncurses5-dev
      - libreadline-dev
      - libreadlin6-dev
      - libtinfo-dev
      - libyaml-dev
    become: yes
    tags: ruby

    
